### ISSUE TITLE
Loading existing signature from SVG text

### ISSUE THREAD

**Issue by ExtremeKaos** [gcacace/android-signaturepad#100]
Improve/Tip ?? : Actually only exists setSignatureBitmap to load an existing signature. 
I have tried to parse in memory stream using com.larvalabs.svgandroid.SVGParser with no luck, the signature have bad definition.

Thanks for any advice....really.

**Comment by gcacace** [comment]
Fixed in 87dd157dabd1303fdbd9a05582147352204d2fdb
