### ISSUE TITLE
onSigned issue

### ISSUE THREAD

**Issue by tagganesh** [gcacace/android-signaturepad#11]
When we just touch the signaturepad and have not drawn our signature, onSigned callback gets executed.

**Comment by gcacace** [comment]
Fixed in https://github.com/gcacace/android-signaturepad/commit/2f8a134dd7cc2a34d25eb0dc3e92a23bff0e0bf9.

**Comment by jairrab** [comment]
Thanks for the library. Touching the pad causes the onSigned to get called. The fix mentioned above sets the isEmpty flag to false during MotionEvent.ACTION_MOVE, which happens as soon as the pad is touched. This doesn't seem to help the issue at all.

**Comment by daniestrella1** [comment]
+1
This issue must be reopened, onSigned listener is called multiple times during touching event.
