### ISSUE TITLE
Cannot Go to Next Page from The signature Pad. The App Crush.

### ISSUE THREAD

**Issue by kyilintun2017** [gcacace/android-signaturepad#112]
I add extra button and go to another form from signature pad. It work but after a few seconds it crush. Can advise?
from here
![image](https://user-images.githubusercontent.com/26317504/36524731-13822f98-17e2-11e8-901d-5d728761b94c.png)
to there and show like this. don't know how
![image](https://user-images.githubusercontent.com/26317504/36524787-4b839ad0-17e2-11e8-8aee-8904eba3516b.png)

Code 
# newA[the Activity of New Form]
public class newA extends Activity {
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout);}
}
# Code from MainActivity
    private void View(){
        Button Test= (Button) (findViewById(R.id.Test_button));
        Test.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onAddRecord();
            }
        });

    }

    private void onAddRecord() {
        Intent intent = new Intent(MainActivity.this, newA.class);
        startActivity(intent);
    }

**Comment by gcacace** [comment]
Hello,

could you please provide a stack trace of your app when it crashes?

**Comment by kyilintun2017** [comment]
03-14 14:26:53.037 23003-23003/com.example.kyilintun.surveysoftware E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.example.kyilintun.surveysoftware, PID: 23003
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.gcacace.signaturepad.views.SignaturePad.setOnSignedListener(com.github.gcacace.signaturepad.views.SignaturePad$OnSignedListener)' on a null object reference

**Comment by kyilintun2017** [comment]
sry for late reply. and thanks the issues still open!

**Comment by kyilintun2017** [comment]
The issue already solved by my self, i use different approach and i am currently able to use the signature pad thanks!

**Comment by starman1108** [comment]
@kyilintun2017 Would your code share? Now I am seeing the same errors.

**Comment by WPSeven** [comment]
Use the below property in your SignaturePad view. In my case, it was working.

`android:saveEnabled="false"`
