### ISSUE TITLE
Pom.xml 

### ISSUE THREAD

**Issue by devamitkumartiwari** [gcacace/android-signaturepad#115]
When I am build gradle timeout message shown and error shows 
HttpRequestException: Could not HEAD 'https://jitpack.io/com/github/gcacace/signature-pad/1.2.1/signature-pad-1.2.1.pom'

**Comment by edgarmiro** [comment]
It happens the same to me. This url does not work [https://jitpack.io/com/github/gcacace/signature-pad/1.2.1/signature-pad-1.2.1.pom](https://jitpack.io/com/github/gcacace/signature-pad/1.2.1/signature-pad-1.2.1.pom)

**Comment by gcacace** [comment]
Please try with latest version.
