### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by nambv** [gcacace/android-signaturepad#13]
It would be awesome to have gradle support for easily integration of this library into any project.

**Comment by nambv** [comment]
@gcacace

**Comment by gcacace** [comment]
I am working on that, sooner the package will be available on Maven Central.

**Comment by Qinwroks** [comment]
great!

**Comment by inktomi** [comment]
+1 this would be great :)

**Comment by gcacace** [comment]
Thanks to @inktomi I have published the library to maven central and updated README.md with installation guide. Please test it so I can close the issue.

**Comment by vzsg** [comment]
Hi, the artifact ID is wrong in the Gradle part of the readme, it should say:

`compile 'com.github.gcacace:signature-pad:1.0.0'` instead of `android-signaturepad`.

Otherwise, it seems to work :)

**Comment by gcacace** [comment]
Fixed, thanks!
