### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by vishalp360** [gcacace/android-signaturepad#130]
Hi,
![image](https://user-images.githubusercontent.com/46594609/58659908-bf78f900-8341-11e9-99b8-d83ee99e7a32.png)

Code works fine using below dependency but when we set compiledsdk to 27 or 28 (default in latest android studio) it gives duplicate class errors. Please advise.
Dependency:
implementation 'com.android.support:appcompat-v7:25.0.0'
implementation 'com.android.support:appcompat-v7:26.0.0'

**Comment by ekoleszar** [comment]
The answer is in #118

**Comment by gcacace** [comment]
Duplicate issue.
