### ISSUE TITLE
Option to get Signature with it's background bitmap

### ISSUE THREAD

**Issue by pixelknight** [gcacace/android-signaturepad#14]
Would be nice if we had the option to Save the bitmap with the specified background instead of just a bitmap of the signature.

**Comment by gcacace** [comment]
You could use `getTransparentSignatureBitmap()` to get a transparent bitmap and add your custom background.

**Comment by pixelknight** [comment]
Ahh thank you, I didn't spot that method in the code, brilliant, thanks.
