### ISSUE TITLE
Not save .jpg or SVG file

### ISSUE THREAD

**Issue by adityagangasagar** [gcacace/android-signaturepad#150]
after writing something on pad is not storing on any device location

**Comment by PieterPicup** [comment]
@adityagangasagar the signature pad does not save anything to the devices storage. It only keeps the view's bitmap in memory. You have to implement your own methods of retrieving the bitmap from the signature pad view and saving it to storage.
Please see the example app for an idea on how to do that.

**Comment by gcacace** [comment]
Please see how to save a signature in the Example application.
