### ISSUE TITLE
Adjust getTransparentSignatureBitmap()

### ISSUE THREAD

**Issue by janngabriel** [gcacace/android-signaturepad#20]
Im sorry for open an Issue to do this, but i dont really know how GitHub works :D

This is a suggestion to put in getTransparentSignatureBitmap() method:

   public static Bitmap TrimImage(Bitmap bmp) {
        int imgHeight = bmp.getHeight();
        int imgWidth  = bmp.getWidth();

        //TRIM WIDTH
        int width  = 0;
        for(int i = 0; i < imgHeight; i++) {
            for(int j = imgWidth - 1; j >= 0; j--) {
                if(bmp.getPixel(j, i) != Color.TRANSPARENT &&
                        j > width) {
                    width = j;
                    break;
                }
            }
        }
        //TRIM HEIGHT
        int height = 0;
        for(int i = 0; i < imgWidth; i++) {
            for(int j = imgHeight - 1; j >= 0; j--) {
                if(bmp.getPixel(i, j) != Color.TRANSPARENT &&
                        j > height) {
                    height = j;
                    break;
                }
            }
        }

        return Bitmap.createBitmap(bmp, 0,0,width, height);
    }

This will get just the Signature image, not returning the white/transparent space. A better result for the method 

Hope it helps someone

**Comment by guicunha** [comment]
i'll try it, maybe it can help me a lot =D

**Comment by janngabriel** [comment]
it get only the drawed area

**Comment by gcacace** [comment]
Hi, could you please create a pull request implementing a method ovverride called `getTransparentSignatureBitmap(boolean trimBlankSpace)`? It would be great! :wink:
