### ISSUE TITLE
SignaturePad doesn't work properly when is inside ScrollView

### ISSUE THREAD

**Issue by joanebrown** [gcacace/android-signaturepad#23]
Hi,

I tried to use your library, but doesn't work properly on my Samsumg Note 3, the scroll of the `ScrollView` does not work.

You know why you can be? Can you help me, please?

Thanks for your library :)

**Comment by gcacace** [comment]
Can you please define "doesn't work properly"? If you put the SignaturePad view inside a ScrollView, touching the SignaturePad won't let the ScrollView move, because the touch events are collected to draw the signature.

**Comment by joanebrown** [comment]
I have a form very long and does not allow me to move the scroll from any point on the screen. I know that inside SignaturePad it will not work, but I've test outside, and the scroll doesn't work.

**Comment by danielsotopino** [comment]
I've putted it on a scrollview and works ok.

**Comment by JeanChristophePalyart** [comment]
try to put in the Scrollview:
`android:fillViewport="true"`
and int the SignaturePad
`android:minHeight="250dp"`

Worked for me

**Comment by Achref001** [comment]
@danielsotopino  try on a small screen and it will not work , the issue is not with SignaturePad , you could easily reproduce this issue when having a scrollView inside a ListView
