### ISSUE TITLE
eraser

### ISSUE THREAD

**Issue by KjunLee** [gcacace/android-signaturepad#26]
I need to remove a specific area . Not the entire area.
So i tried changing pen color with transparent, but it clear a rect area.
I just need to remove specific line.

Please tell me how to do it.

**Comment by gcacace** [comment]
The SignatureView was designed to capture signatures. Single line removal is not part of current features. Feel free to make a pull request if you decide to implement that.

**Comment by KjunLee** [comment]
thanks for comment.
