### ISSUE TITLE
Multiple lines on signature

### ISSUE THREAD

**Issue by MatthewCawley** [gcacace/android-signaturepad#28]
The moment you life your finger the saveSignature function is called. The saveSignature function never fires again unless a clear is called. As a result, any signatures that require lifting the finger, do not render anything after the life when saved.

Can the touch fire save after every finger lift or after a delay (i.e. if the finger does not touch the screen in x seconds, then save)

**Comment by gcacace** [comment]
the `onSigned()` listener function is called every time a line is drawn on the signature pad. There is no way to recognize a "complete" signature. According to the provided Example application, a button to confirm the signature is enabled when `onSigned()` is called, allowing the user to submit the signature only when the signature pad is not empty.

If you prefer, setup a timer and reset it every time `onSigned()` is called.

**Comment by MatthewCawley** [comment]
Hi again,

The issue I am having is due to the following

    private void setIsEmpty(boolean newValue) {
        if (mIsEmpty != newValue) {
            mIsEmpty = newValue;

            if (mOnSignedListener != null) {
                if (mIsEmpty) {
                    mOnSignedListener.onClear();
                } else {
                    mOnSignedListener.onSigned();
                }
            }
        }
    }


The `setIsEmpty(false)` is called after the first touchUpEvent, which means the means that the OnSignedLister can not fire again until it has been cleared. The setisEmpty is a private method and cannot be access by the implementing class. My solution would be to remove the uppermost if statement so that we just have.

    private void setIsEmpty(boolean newValue) {
         if (mOnSignedListener != null) {
             if (mIsEmpty) {
                 mOnSignedListener.onClear();
             } else {
                 mOnSignedListener.onSigned();
             }
         }
    }

**Comment by gcacace** [comment]
You're right, would you mind to create a pull request, please?
