### ISSUE TITLE
Call setSignatureBitmap() before view measurement

### ISSUE THREAD

**Issue by gcacace** [gcacace/android-signaturepad#3]
Calling setSignatureBitmap() on onCreate() of an Activity will result in a crash, because getWidth() and getHeight() of SignaturePad are null.

**Comment by trungptdhcn** [comment]
When this bug fixed?

**Comment by jakeingit** [comment]
I am not the lead dev on this. I'm not sure when it will be fixed.
J

**Comment by trungptdhcn** [comment]
Ok, so i will reseach and maintain it. Thank

**Comment by gcacace** [comment]
Hi, unfortunately at the moment I have no time to fix it. It would be great if someone could take care of this, making a pull request against this issue.

**Comment by luixal** [comment]
Not sure if this is really a bug, I think the propper way would be to call `setSignatureBitmap` inside the `onStart` or `onViewCreated' method.

**Comment by TinasheMzondiwa** [comment]
This will avoid the crash:

signaturePad.post(new Runnable() {
          @Override
          public void run() {
                signaturePad.setSignatureBitmap(currentSignature);
          }
 });

**Comment by z0lope0z** [comment]
+1 @TinasheMzondiwa 's solution works. I can wrap the setSignatureBitmap lines inside a Runnable and send it to post. 

I think this is because of a race condition between the signaturePad rendering itself and the bitmap being set

**Comment by pla1** [comment]
Thanks @TinasheMzondiwa for the `new Runnable` work-around.
