### ISSUE TITLE
OnSignedListener on a null object reference

### ISSUE THREAD

**Issue by AndreyNazarchuk** [gcacace/android-signaturepad#61]
**When trying to start the activity with this view in it:**
`<RelativeLayout
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_above="@+id/buttons_container"
        android:id="@+id/signature_pad_container">

        <FrameLayout
            android:layout_width="fill_parent"
            android:layout_height="1dp"
            android:background="@android:color/darker_gray"
            android:layout_marginBottom="8dp"
            android:layout_above="@+id/signature_pad_description" />

        <TextView
            android:id="@+id/signature_pad_description"
            android:layout_width="wrap_content"
            android:layout_centerHorizontal="true"
            android:layout_height="wrap_content"
            android:textColor="@android:color/darker_gray"
            android:layout_marginBottom="16dp"
            android:layout_alignParentBottom="true"
            android:text="@string/agreementR" />

        <com.github.gcacace.signaturepad.views.SignaturePad
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/signature_pad"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:penColor="@android:color/black"
            />
    </RelativeLayout>`

**I get this error:** 
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.portalcarriers.portal/com.portalcarriers.portal.SignActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.gcacace.signaturepad.views.SignaturePad.setOnSignedListener(com.github.gcacace.signaturepad.views.SignaturePad$OnSignedListener)' on a null object reference
                                                                               at ... 
com.portalcarriers.portal.SignActivity.onCreate(SignActivity.java:41)
                                                                               at ... `

**Here's the onCreate for the activity:**
`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_scan);
        this.extras = getIntent().getExtras();
        this.type = this.extras.getInt("type");

        TextView agreement = (TextView) findViewById(R.id.signature_pad_description);
        if(type == 1){
            agreement.setText(R.string.agreementR);
        }
        else if(type == 2){
            agreement.setText(R.string.agreementD);
        }
        mSignaturePad = (SignaturePad) findViewById(R.id.signature_pad);
        //LINE 41-----mSignaturePad.setOnSignedListener(new SignaturePad.OnSignedListener() {
            @Override
            public void onStartSigning() {
            }

            @Override
            public void onSigned() {
                mSaveButton.setEnabled(true);
                mClearButton.setEnabled(true);
            }

            @Override
            public void onClear() {
                mSaveButton.setEnabled(false);
                mClearButton.setEnabled(false);
            }
        });

        mClearButton = (Button) findViewById(R.id.clear_button);
        mSaveButton = (Button) findViewById(R.id.save_button);

        mClearButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mSignaturePad.clear();
            }
        });

        mSaveButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Bitmap signatureBitmap = mSignaturePad.getTransparentSignatureBitmap();
                ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
                signatureBitmap.compress(Bitmap.CompressFormat.PNG, 100, byteArrayOutputStream);
                byte[] byteArray = byteArrayOutputStream .toByteArray();
                String encoded = Base64.encodeToString(byteArray, Base64.DEFAULT);
                Intent returnIntent = new Intent();
                returnIntent.putExtra("img", encoded);
                setResult(Activity.RESULT_OK, returnIntent);
                finish();
            }
        });
    }`

**Comment by AndreyNazarchuk** [comment]
nevermind, i was setting the wrong ContentView

**Comment by shitab14** [comment]
Hi @AndreyNazarchuk ,
I am having the same error
        "Attempt to invoke virtual method 'void com.github.gcacace.signaturepad.views.SignaturePad.setOnSignedListener(com.github.gcacace.signaturepad.views.SignaturePad$OnSignedListener)' on a null object reference"

Can you please state what solved your problem? thanks

**Comment by uziins** [comment]
> Hi @AndreyNazarchuk ,
> I am having the same error
> "Attempt to invoke virtual method 'void com.github.gcacace.signaturepad.views.SignaturePad.setOnSignedListener(com.github.gcacace.signaturepad.views.SignaturePad$OnSignedListener)' on a null object reference"
> 
> Can you please state what solved your problem? thanks

Seems that you missed something on your `onCreate ` method. Check your content layout reference.
