### ISSUE TITLE
SignaturePad getBitmap not working in OnSignedListener

### ISSUE THREAD

**Issue by peterchaula** [gcacace/android-signaturepad#69]
@Override
            public void onSigned() {
                   Bitmap signatureBitmap = mSignaturePad.getTransparentSignatureBitmap();

 This bitmap shows a very small signature

**Comment by gcacace** [comment]
Hello,

The size of the signature depends on the size of the view on the phone screen. You can then apply any type of transformation to adapt it to your needs. What I can suggest is to get the SVG version, so you won't lose in terms of quality, when resizing.
