### ISSUE TITLE
save bitmap as file to local,background is black

### ISSUE THREAD

**Issue by QinAndroid** [gcacace/android-signaturepad#80]
When i save the signature bitmap as a file to storage,the local file is changed black ,can't see the signature content

**Comment by Mauker1** [comment]
I suggest that you also post a snippet of how are you trying to achieve that, so the devs can look further into this issue.

**Comment by QinAndroid** [comment]
public void saveBitmap(Bitmap bm) {
        Bitmap bitmap = Bitmap.createBitmap(bm.getWidth(),bm.getHeight(), Bitmap.Config.ARGB_8888);
        KLog.e("llllll--->",getActivity().getExternalCacheDir());
        File f = new File(getActivity().getExternalCacheDir(), "ssss.png");
        if (f.exists()) {
            f.delete();
        }
        try {
            FileOutputStream out = new FileOutputStream(f);
            bitmap.compress(Bitmap.CompressFormat.JPEG, 100, out);
            out.flush();
            out.close();
            KLog.i("ssss", "已经保存");
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

save bitmap to sdCard,can't see the signature content,photo is all black

**Comment by ABritishPerson** [comment]
You just need to change Bitmap.CompressFormat.JPEG to Bitmap.CompressFormat.PNG

**Comment by gcacace** [comment]
As pointed out by @ABritishPerson, the format was wrong: JPEG doesn't have the concept of transparency. You must save it as PNG if you want to preserve the transparency.

**Comment by mwshubham** [comment]
If someone want to save bitmap

```
val bitmap = signature_pad.getTransparentSignatureBitmap(true)
                val file = FileUtil.createCacheFile(activity!!, EnumUtils.FileType.IMAGE.ordinal, "digital_signature.png")
                file.saveBitmap(bitmap)
```


```
 fun createCacheFile(context: Context, fileType: Int, fileName: String, folderName: String = "BlahBlah"): File {
        val dirSuffix = when (fileType) {
            EnumUtils.FileType.TEXT.ordinal -> DIR_SUFFIX_TEXT
            EnumUtils.FileType.IMAGE.ordinal -> DIR_SUFFIX_IMAGES
            EnumUtils.FileType.AUDIO.ordinal -> DIR_SUFFIX_AUDIOS
//            EnumUtils.ContentType.DOCUMENT.ordinal -> DIR_SUFFIX_DOCUMENTS
            EnumUtils.FileType.VIDEO.ordinal -> DIR_SUFFIX_VIDEOS
            else -> DIR_SUFFIX_FILES
        }
        val dir = File(context.cacheDir.toString() + "/" + folderName + dirSuffix)
        dir.mkdirs()
        return File(dir.absolutePath, fileName)
    }
```
Kotlin Extention function
```
fun File.saveBitmap(bitmap: Bitmap) {
    val bos = ByteArrayOutputStream()
    bitmap.compress(CompressFormat.PNG, 0 /*ignored for PNG*/, bos)
    val bitmapData = bos.toByteArray()
    val byteArrayInputStream = ByteArrayInputStream(bitmapData)
    byteArrayInputStream.use { input ->
        this.outputStream().use { fileOut ->
            input.copyTo(fileOut)
        }
    }
}
```
