### ISSUE TITLE
Detect if the signature was enough pixels

### ISSUE THREAD

**Issue by gupta11** [gcacace/android-signaturepad#84]
Use case: The user just touches the screens and clicks save. 

I want to able to tell if the signature entered was enough to be considered a signature, perhaps by amount of pixels or some sort of indication. Is that something that is possible ? @gcacace

**Comment by gupta11** [comment]
Was there any update on this issue?

**Comment by Dhrupal** [comment]
I found the solution.
private boolean checkWeatherSignedOrNot() {
        Bitmap signatureBitmap = mSignaturePad.getSignatureBitmap();

        int redBucket = 0;
        int greenBucket = 0;
        int blueBucket = 0;

        int pixelCount = signatureBitmap.getWidth() * signatureBitmap.getHeight();
        int[] pixels = new int[pixelCount];
        signatureBitmap.getPixels(pixels, 0, signatureBitmap.getWidth(), 0, 0, signatureBitmap.getWidth(), signatureBitmap.getHeight());

        for (int y = 0, h = signatureBitmap.getHeight(); y < h; y++) {
            for (int x = 0, w = signatureBitmap.getWidth(); x < w; x++) {
                int color = pixels[x + y * w]; // x + y * width
                redBucket += (color >> 16) & 0xFF; // Color.red
                greenBucket += (color >> 8) & 0xFF; // Color.greed
                blueBucket += (color & 0xFF); // Color.blue
            }
        }

        if (redBucket == greenBucket && redBucket == blueBucket) {
            return false;
        } else {
            return true;
        }
    }

**Comment by Tgo1014** [comment]
That really should be implemented. Maybe you should make a pull request!

**Comment by Mauker1** [comment]
That's an interesting feature to have indeed.

**Comment by tplive** [comment]
Wait, how does this work..?

**Comment by brianfox201** [comment]
private boolean checkWeatherSignedOrNot() {
        Bitmap signedTransparentBitmap = mSignaturePad.getTransparentSignatureBitmap();
        Bitmap emptyBitmap = Bitmap.createBitmap(signedTransparentBitmap.getWidth(), signedTransparentBitmap.getHeight(), signedTransparentBitmap.getConfig());
        if (signedTransparentBitmap.sameAs(emptyBitmap)) {
            // non signed bitmap.
            return false;
        }
        return true;
    }

This code will check if Bitmap contains pixels or not. It will return false if the Bitmap does not have a valid pixels.
